# Smart Waste Management - Environment Setup Script
# Run this script to create your .env file automatically

Write-Host "🔧 Smart Waste Management - Environment Setup" -ForegroundColor Cyan
Write-Host "================================================" -ForegroundColor Cyan
Write-Host ""

# Check if .env already exists
if (Test-Path ".env") {
    Write-Host "⚠️  .env file already exists!" -ForegroundColor Yellow
    $overwrite = Read-Host "Do you want to overwrite it? (y/N)"
    if ($overwrite -ne "y" -and $overwrite -ne "Y") {
        Write-Host "❌ Setup cancelled. Keeping existing .env file." -ForegroundColor Red
        exit
    }
}

# Create .env file
Write-Host "📝 Creating .env file..." -ForegroundColor Green

$envContent = @"
# Smart Waste Management System - Environment Configuration
# Auto-generated by setup-env.ps1

# ===========================================
# DATABASE CONFIGURATION
# ===========================================
MONGODB_URI=mongodb+srv://hashan9053_db_user:Iw9jrhQraKqCmIrV@smart-waste-cluster.1unznof.mongodb.net/smartWaste?retryWrites=true&w=majority&appName=smart-waste-cluster

# ===========================================
# SERVER CONFIGURATION
# ===========================================
API_PORT=3000
NODE_ENV=development

# ===========================================
# JWT AUTHENTICATION
# ===========================================
JWT_SECRET=your-super-secret-jwt-key-here-change-this-in-production
JWT_EXPIRES_IN=24h

# ===========================================
# CORS CONFIGURATION
# ===========================================
CORS_ORIGIN=http://localhost:3000,http://localhost:3001,http://localhost:5173

# ===========================================
# REDIS CONFIGURATION (Optional - commented out)
# ===========================================
# REDIS_URL=redis://localhost:6379

# ===========================================
# MQTT CONFIGURATION (Optional - commented out)
# ===========================================
# MQTT_BROKER_URL=mqtt://localhost:1883
# MQTT_CLIENT_ID=smart-waste-backend

# ===========================================
# ML SERVICE CONFIGURATION
# ===========================================
ML_SERVICE_URL=http://localhost:8888
ML_SERVICE_API_KEY=ml-secret-token

# ===========================================
# MONITORING CONFIGURATION
# ===========================================
LOG_LEVEL=info
ENABLE_METRICS=false
"@

# Write to .env file
$envContent | Out-File -FilePath ".env" -Encoding UTF8

Write-Host "✅ .env file created successfully!" -ForegroundColor Green
Write-Host ""
Write-Host "📋 Configuration:" -ForegroundColor Cyan
Write-Host "  - MongoDB: MongoDB Atlas (smartWaste database)" -ForegroundColor White
Write-Host "  - Port: 3000" -ForegroundColor White
Write-Host "  - Environment: development" -ForegroundColor White
Write-Host "  - Redis: Disabled (optional)" -ForegroundColor White
Write-Host "  - MQTT: Disabled (optional)" -ForegroundColor White
Write-Host ""
Write-Host "⚠️  IMPORTANT NEXT STEPS:" -ForegroundColor Yellow
Write-Host "1. Go to https://cloud.mongodb.com/" -ForegroundColor White
Write-Host "2. Make sure your cluster is ACTIVE (not paused)" -ForegroundColor White
Write-Host "3. Add your IP to Network Access (or use 0.0.0.0/0)" -ForegroundColor White
Write-Host "4. Test connection: node test-db-connection.js" -ForegroundColor White
Write-Host "5. Start backend: npm run dev" -ForegroundColor White
Write-Host ""
Write-Host "✨ Setup complete! Good luck with your project!" -ForegroundColor Green

















































